const CHANGE_CURRENT_SONG = "PLAYER_CHANGE_CURRENT_SONG";
const CHANGE_PLAY_LIST = "PLAYER_CHANGE_PLAY_LIST";
const CHANGE_CURRENT_SONG_INDEX = "PLAYER_CURRENT_SONG_INDEX";
const CHANGE_SEQUENCE_INDEX = "PLAYER_CHANGE_SEQUENCE_INDEX";
const CHANGE_LYRIC_LIST = "PLAYER_CHANGE_LYRIC_LIST";
const CHANGE_CURRENT_LYRIC_INDEX = "PLYAER_CHANGE_LYRIC_INDEX";
export {
    CHANGE_CURRENT_SONG,
    CHANGE_PLAY_LIST,
    CHANGE_CURRENT_SONG_INDEX,
    CHANGE_SEQUENCE_INDEX,
    CHANGE_LYRIC_LIST,
    CHANGE_CURRENT_LYRIC_INDEX
}