export const CHANGE_TOP_BANNERS = "RECOMMEND_CHANGE_TOP_BANNERS";
export const CHANGE_HOT_RECOMMEND = "RECOMMEND_CHANGE_HOT_RECOMMEND";
export const CHANGE_NEW_ALBUM = "RECOMMEND_CHANGE_NEW_ALBUM";
export const CHANGE_TOP_NEW_LIST = "RECOMMEND_CHANGE_TOP_NEW_LIST";
export const CHANGE_TOP_SURGE_LIST = "RECOMMEND_CHANGE_TOP_SUGER_LIST";
export const CHANGE_TOP_ORIGIN_LIST = "RECOMMEND_CHANGE_TOP_ORIGIN_LIST";
export const CHANGE_IN_SINGER = "RECOMMEND_CHANGE_IN_SINGER";